### PR TITLE
Feature/issue304 individual archives

### PR DESCRIPTION
**Pull request by bowserm**
To hopefully resolve this issue that I opened:
https://github.com/Shazwazza/Articulate/issues/304

Let me know if this was the wrong way to submit a pull request and I'll get it fixed.

Thanks.

### CODE REVIEW

**Comment by bowserm** [comment]
I don't know where my head was when I made this pull request, but the way that it is merged with the Umbraco 8 version of Articulate was not right. This doesn't even build. Sorry about that.

**Comment by Shazwazza** [comment]
Hi, i know this is super old :/ sorry about that! I think i just noticed when you posted the last message that this PR wasn't quite right so I just left this here. But just circling back to this.... is this still a feature that needs to be fixed/created?

**Comment by bowserm** [comment]
I believe so, but its been so long for me too. When I get some space, I need to look into the current status of Articulate and then find out if what I did here still makes sense.

**Comment by frederiktoft** [comment]
Just want to chime in and say I would like this feature added. To me it seems as feature wise there is a hole that this PR will fill.

**Comment by Shazwazza** [comment]
Code looks good, i still need to test and get my head back into this but i'll merge since I think i know what's going on. Really sorry for the very long delay and really appreciate the effort! I'll try to test and get a new release out this month

**Pull request merged**
