### PR TITLE
first image extracted from markdown and added to postimage

### PR DESCRIPTION
**Pull request by stokesy43**
Added code to the Markdown api controller which will extract the first image found and add it to the postimage.   Works the same way as the live writer extracts the image out.

Not sure if its the best way of implementing this but wanted to share.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Only issue with this is that it will now show duplicate images when viewing if you are also showing the post image and the blog post which is the case now in all of the themes. 

The way that the Live Writer handles this when it extracts the image is that it sets a class on the image in the RTE so that the first image is hidden. I'll see if i can do the same for this.

**Comment by Shazwazza** [comment]
We also need to check if the extract first image setting on the articulate node is enabled

**Comment by Shazwazza** [comment]
All fixed, thanks for the PR! :)

**Comment by stokesy43** [comment]
No worries, in addition to that change I also added an event handler to add a class make markdown images have the img-responsive class.  In case anyone would like to use it in the same manner the code is:

```
protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            ArticulateOptions.Setup(
                new ArticulateOptions(markdownDeepOptionsCallBack: callback));
                   
        }

        private Action<object> callback = o =>
        {
            var md = (MarkdownDeep.Markdown)o;

            md.PrepareImage = delegate (MarkdownDeep.HtmlTag tag, bool TitledImage)
            {
                tag.attributes.Add("class", "img-responsive");
                return true;
            };

```
        };

**Comment by Shazwazza** [comment]
that's awesome! nice one

**Comment by Shazwazza** [comment]
What I've done currently is actually strip the first image from the markdown ... but maybe that's not the right way to do this since you might actually also want this image in your document.

Ok, i'll create a new issue to make sure I revert that

**Pull request merged**
