### PR TITLE
BlogML Tags Export

### PR DESCRIPTION
**Pull request by nvisage-gf**
Partial support via extension that matches current import; have not implemented to exact schema yet.

### CODE REVIEW

**Comment by Shazwazza** [comment]
So should i consider this still in progress?

**Comment by nvisage-gf** [comment]
I was unsure if Tags should be treated the same way as Categories using refs and collection on document but it appears not as no mention of Tags in specification and existing import code examples just treat them as text values.

This is done apart from perhaps naming things & check that the xs Namespace is okay to use?

**Comment by gavinfaux** [comment]
Not quite done. When importing more than (x) tags in Umbraco a StackOverflow exception is being thrown after publishing during serialisation. Investigating.

**Comment by nvisage-gf** [comment]
Other than facilitating the import of [too many things](https://github.com/Shazwazza/Articulate/issues/241) this is done.

Extensions were written to help migrate content including tags from previous v6 CMS running uBlogsy and rich text based content using tags.

**Comment by Shazwazza** [comment]
amazing work! really sorry i't taken me (1+ yrs ... what!? where has time gone). I'll get this tested and merged in. Thanks again !

**Comment by Shazwazza** [comment]
Merged and tested and awesome work! Will be a nice addition to the upcoming shiny 4.0 release

**Pull request closed without merging**
