### PR TITLE
Resolves #385.

### LINKED ISSUE #385: 404 On  Tags / Category Page after moving content node from root to multisite node
Hi,

Umbraco: 8.14.1
Articulate: 4.3.0

I'm getting a 404 when I try to view the Tags or Categories.

This is a multi-tenant site, I'd created the sample nodes and it created them in the root. I'm pretty sure that the tags/categories page worked at this point. I then moved the blog node under the home page node of one of the sites, the list page and blog page work fine, but I get a 404 on the tags/categories.

I've looked at all the articles with similar problems but didn't find anything to help me.

Does the category page have a hidden node in the umbraco content tree perhaps that I might need to update the parent ?

Many thanks in advance for any help

### PR DESCRIPTION
**Pull request by FloppyChips**
Resolves #385.

### CODE REVIEW

**Comment by FloppyChips** [comment]
Please can we progress this one, we'd like to include this project in our release. Great job by the way!  Regards Stuart

**Comment by Shazwazza** [comment]
Hi thanks for this. It's been a long time since I looked at that code but IIRC there was a reason why 'localhost' needed to be checked there. Any chance you can provide me with some additional context as to these changes while you were debugging? I just don't want to release a breaking change.

**Comment by FloppyChips** [comment]
True this doesn't seem to have changed since first written. We noticed a problem when we added a second domain under the Culture and Hostnames settings in Umbraco, so we now have 1) https://localhost:44300 and 2) https://some_real_domain. I can't say this won't break anything but I think its clear there is some inconsistency between the hosts that are going into the list _urlNames and how they are being matched at the moment. It might be that checking for "localhost" at both points would also be a fix. Note that we wanted to have multiple blogs eventually but at the moment we just moved the Blog from under the root to under a sub-node.

**Comment by FloppyChips** [comment]
I can confirm that

private const string DetectDomainAbsoluteUrl = "localhost";

also works for us if you would rather have that.

**Comment by FloppyChips** [comment]
I have proposed an update where "localhost" is used in the comparison as discussed above, this also works for us.

**Pull request merged**
