### PR TITLE
Master

### PR DESCRIPTION
**Pull request by vnbaaij**
There are now at least three (great) open source packages using the theme functionality: Articulate (obviously), Dialogue and Merchello. (and we are also using it in our closed source project).
A lot of code is copied between the projects to enable the themes. With this pr I have tried to make the theme functionality more generally available by creating a ViewEngine combined with a single folder in which the themes are placed.

Modifications:
-Generalizes Theme functionality by putting them in the Themes folder
-Added ThemeViewEngine to add Themes/{theme} folder to searched Views and Partials folders, Engine added to ApplicationStarted
-Altered PropertyEditorsControllers to  search for themes in Themes folder
-Existing themes are moved to Themes and altered to use this location (Html.ThemedPartial to regular Html.Partial)
-Controllers are altered to use Themes (no more GetThemeViewPath)
-Adjusted PathHelper to search in the right place (just in case)
-Html Helpers etc which were used in original theme approach are left untouched for now. These could be removed at a later state.

I wanted to use App_Themes folder, but it is protected and can therefore not be used. Choose Themes instead.

### CODE REVIEW

**Comment by Shazwazza** [comment]
It's interesting! but of course these are massive breaking changes :)

The other thing to note is that there's a reason for having all items for a package in a single App_Plugins folder. We don't want to be scattering around files for a single package. All of it's files should be contained in App_Plugins/MyPackage/* and then of course DLLs go in to the the /bin

If we now have a 'Themes' folder, now we'd have 2 folders to distribute files for a single package to.

I can see there might be a need to better support a 'theme' folder for developers to be able to reorganize their view files between packages into a structure that is more manageable for them but I think this might be a case by case basis.

To do this properly I think this is what would need to be done:

* Create a ThemeManagerResolver which inherits from SingleObjectResolverBase which resolves an IThemeManager
     * This means it's configurable/replaceable during Umbraco startup
     * The IThemeManager would: 
        * get/set the theme folder for any given package (i.e. a Dictionary<string, string> of package path + theme path
        * return the list of all installed themes for a given package
* During startup a developer can specify the theme path for any given package - which of course they could all set to the same location
* By default, no entries will be made in the IThemeManager so when a package or view engine (etc...) asked the IThemeManager for the theme path of a package it will return the convention based path: "~/App_Plugins/MyPackage" + "/Themes"
* The theme drop down list would be created based on the results from IThemeManager
* The theme name should be stored in the DataTokens of the route using an ActionFilter, model binder or something... should be set before the controller and be done in a single place instead of replicating that logic in all controllers
* The theme view engine would use the DataToken value set with a combination of the IThemeManager to determine the view to render

With all of the above in place, this could be done without any breaking changes and also allow for more flexibility for end-users as well as maintaining an existing and consistent structure for package developers. If an end-user wants to move everything to a ~/Theme folder, then they can do that if they want to. For all of the extension methods like ThemedPartial, these would be marked as obsolete and just call Partial behind the scenes to maintain compatibility.

**Comment by vnbaaij** [comment]
Thanks for your extensive comment. I didn't take backward compatibility into the picture when thinking this up.
I agree on the distribution to 2 folders problem. Not handy to scatter around files.
If your proposed changes are done, do you think this would be more of a core thing then? 

I'll see if I can code up the steps you describe, but not sure if I can do all of them. Are you willing to assist if/when needed?

**Comment by vnbaaij** [comment]
Ok, made a start with your workitems. As I said, I think I don't have the knowledge to do it all :) 
Below is the ThemaManagerResolver class. Think it's ok like that?
You say it's configurable/replaceable during Umbraco startup. How do I plug it in?

```c#
using Umbraco.Core.ObjectResolution;

namespace Articulate
{
    /// <summary>
    /// Resolves the <see cref="IThemeManager"/> implementation.
    /// </summary>
    public class ThemeManagerResolver : SingleObjectResolverBase<ThemeManagerResolver, IThemeManager>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThemeManagerResolver"/> class with an <see cref="IThemeManager"/> implementation.
        /// </summary>
        /// <param name="helper">The <see cref="IThemeManager"/> implementation.</param>
        internal ThemeManagerResolver(IThemeManager manager)
            : base(manager)
        {
        }

        /// <summary>
        /// Can be used at runtime to set a custom IThemeManager at app startup
        /// </summary>
        /// <param name="serverRegistrar"></param>
        public void SetThemeManager(IThemeManager manager)
        {
            Value = manager;
        }

        /// <summary>
        /// Gets the <see cref="IThemeManager"/> implementation.
        /// </summary>
        public IThemeManager ThemeManager
        {
            get { return Value; }
        }
    }
}
```

The IThemeManager: This is getting harder already. Should it be something like this?
```c#
public interface IThemeManager
    {
        /// <summary>
        /// Dictonary containing all package paths and theme paths
        /// </summary>
        Dictionary<string, string> ThemePathsForPackage { get; set; }

        /// <summary>
        /// return the list of all installed themes for a given package
        /// </summary>
        /// <param name="packageName">the package name</param>
        /// <returns></returns>
        IEnumerable<string> GetAllThemesForPackage(string packageName);
    }
```

•During startup a developer can specify the theme path for any given package - which of course they could all set to the same location - How would I do this?

**Comment by Shazwazza** [comment]
Good start. The `ThemeManagerResolver` looks good. The way you would normally replace or update this is during the `ApplicationStarting` method of an instance of `ApplicationEventHandler`. However since we are doing this outside of the umbraco core (currently), you need to create it in the method 'ApplicationInitialized` like:

    ThemeManagerResolver .Current = new ThemeManagerResolver (new DefaultThemeManager(...));

Then if people wanted to replace the IThemeManager during startup, in the `ApplicationStarting` method, they could do:

    ThemeManagerResolver.Current.SetThemeManager(new CustomThemeManager(...));

In the Umbraco core, resolvers are normally created in the `IBootManager`, but again, since this is outside of the core, we'll use `ApplicationInitialized` for the moment.

The `IThemeManager` needs some minor changes: the `ThemePathsForPackage` should be removed, this would allow runtime chages to this dictionary after startup which we cannot have happen (cannot be mutable after startup). So we need to just change this to have two methods: `AddOrUpdatePackageTheme(string, string)` and `RemovePackageTheme(string)` , it will be up to the implementation of IThemeManager to ensure that things cannot be changed after started. This can be achieved by wrapping the internal dictionary updates with:

    using (Resolution.Configuration) { ... }

**Comment by vnbaaij** [comment]
Made a new commit which reverts the earlier changes and implements the first steps of your suggested approach

**Pull request closed without merging**
