### PR TITLE
Authors list and author pages (issue #10)

### PR DESCRIPTION
**Pull request by AndyButland**
Been having a play with this Shannon to likely take a look at using it for a new team blog site at work.  Have forked and likely to make some customisations but this one looked to be a general one and on your issue tracker, hence the PR.

It implements pages for author - at `/authors/` - that lists all the authors that have actual authors pages along with their posts in the same manner as `/tags/` does.

And then a page for the author at `/authors/author-name`, displaying their details (bio, website, image) and a paged lists of their posts.

Couple of other points to note:

- I refactored some common code for doing paged lists into a base controller
- I renamed `AuthorModel` (that was attached to `PostModel` as a simple class with a few properties) to `PostAuthorModel` so could have `AuthorModel` as the model for the author page itself (and thus inherit from MasterModel).

### CODE REVIEW

**Comment by vincentparrett** [comment]
Any movement on this PR? I could really use this feature.

**Comment by biapar** [comment]
+1

**Comment by Shazwazza** [comment]
Hey @AndyButland I know this is a pain but any chance you can merge in the main branch into yours and re-push so that it merges nicely? (or rebase)

**Comment by AndyButland** [comment]
Yes, OK - will take a look.

**Comment by AndyButland** [comment]
Have closed this and will resubmit following the rebase.

**Comment by AndyButland** [comment]
Re-submitted under https://github.com/Shazwazza/Articulate/pull/142

**Pull request closed without merging**
