### PR TITLE
Authors list and author pages (issue #10)

### PR DESCRIPTION
**Pull request by AndyButland**
Resubmitted https://github.com/Shazwazza/Articulate/pull/83 following rebase from master branch.  See that closed PR for details.

Afraid the commit history is a bit of a mess due to the rebase, solution restructure in the meantime and some config files I'd inadvertently checked in previously.  But the file changes requested to be pulled in I believe are right.  Hope that's OK.

### CODE REVIEW

**Comment by tmoffett-centrify** [comment]
@AndyButland and @Shazwazza is there any plan to review and merge in this PR?  This seems like a necessary feature for a blog to have that is missing from Articulate.  At least, I haven't seen something like this in the 2.0.5 version I am using.  Is a similar feature already developed or in the works?

**Comment by abhilashca** [comment]
Hello @AndyButland great changeset. I have merged your changes with latest version of Articulate and submitted a pull request.
@Shazwazza it would be really great, if you could review the changes.
Thanks a lot.

**Comment by Shazwazza** [comment]
Hi, yes I am aware, i currently don't have time to do this right now but i will review as soon as I do. There's a lot of changes that need to be reviewed for this next major release.

**Comment by Shazwazza** [comment]
Just going to close this PR in favor of the more recent one, I've added a few comments on there which need to be fixed up before i can merge. Thank you both for all of your help here!!

**Pull request closed without merging**
