### PR TITLE
Added contentpicker for selecting Articulate root node: Issue #115

### PR DESCRIPTION
**Pull request by simonech**
Added content picker for selecting the root node during the import.
Please Shannon have a look and see if that's the right way to implement it.
It works, but not sure is the proper way to do it :)

### CODE REVIEW

**Comment by simonech** [comment]
@Shazwazza : any comment on this?

**Comment by Shazwazza** [comment]
Sorry! Will get to this tomorrow :) I'm on holidays on Monday for a couple of weeks so will be sure to get back to you before I go.

**Comment by simonech** [comment]
:+1:

**Comment by simonech** [comment]
Guess you forgot to do that before leaving for holidays :) No problem...

**Comment by simonech** [comment]
@Shazwazza news? :)

**Comment by Shazwazza** [comment]
Holidays ;) will get this all done before NY. Have a great xmas!

**Comment by simonech** [comment]
Happy holidays you too! :-)

**Comment by Shazwazza** [comment]
Code looks great! love how easy it is to implement this stuff nowadays :) I'll pull it in and test. Thx!

**Comment by simonech** [comment]
Thx!! :smile: 
Happy New Year!!

**Pull request merged**
