### PR TITLE
Pagination - Sort/Take issues

### PR DESCRIPTION
**Pull request by nvisage-gf**
#217 Breaks paging on ArticulateController RenderView, the pager works but the ListModel always returns first page results. 

Temporary HttpContext fix in place till Skip/Take logic reviewed

### CODE REVIEW

**Comment by KrisJanssen** [comment]
I can confirm I also got hit by this. Noticed when I recompiled Articulate.dll from source for some custom tweaking. Was previously running the latest version in the Umb package repo.

**Comment by Shazwazza** [comment]
Thanks for reporting, i'll have a look and see what the best way to fix it all is.

**Comment by nvisage-gf** [comment]
Fixed by amending ArticulateController to call GetRecentPosts, all other scenarios go through helper methods that Sort already. 

Is there a way to pass a maxPosts parameter somewhere?

**Comment by Shazwazza** [comment]
I can replicate the issue, it's in a couple of places actually so i'll fix this up

**Comment by Shazwazza** [comment]
I've pushed a separate fix for this - the one part uses the same concept as you did but with proper paging paramaters now, the other problem was posts by tag/category which didn't do paging well, now it does the correct db level paging.

**Comment by nvisage-gf** [comment]
Thank you.

A minor [amend](https://github.com/nvisage-gf/Articulate/commit/1c087cc06aef31f03583d0355c5d7489ca135773) is required if doing a release build (commit linked is just before the 7.6 amends if anyone needs).

**Pull request closed without merging**
